import '../imports/ui/layouts/HomeLayout.html';
import '../imports/ui/layouts/MainLayout.html';
import '../imports/ui/layouts/Header.html';
import '../imports/ui/layouts/SideNav.html';
import '../imports/ui/menu/menu.js';
import '../imports/ui/shopping-list/shopping-list.js';
import '../imports/ui/recipes/recipes.js';
import '../imports/ui/recipes/recipe.js';
import '../imports/ui/recipes/recipesingle.js'
import '../imports/startup/client/routes.js';
import '../imports/api/recipes/recipes.js';
